
["Currency Configuration"]
	#Currency - defining the names and values of each currency item in the mod. NAME:VALUE, Value must be within 0.01 to 2147483647.99
	currency = ["Um Real:1.00", "Cinco Reais:5.00", "Dez Reais:10.00", "Vinte Reais:20.00", "Cinquenta Reais:50.00", "Cem Reais:100.00"]

